FROM microsoft/dotnet:2.2-aspnetcore-runtime

WORKDIR /app

COPY ./app .

VOLUME /logs
ENV LogDir /logs
VOLUME /serverLogs
ENV ServerLogsDir /serverLogs

EXPOSE 80

ENTRYPOINT ["dotnet", "BTStatsCore.dll"]
