FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY ./app .

VOLUME /logs
ENV LogDir /logs
VOLUME /serverLogs
ENV ServerLogsDir /serverLogs
ENV ServePort 80

ENTRYPOINT ["dotnet", "BTStatsCore.dll"]
